---
title: "Analysis of predicted protein levels in tumour samples"
author: Nicolai Vitt
date: "`r format(Sys.time(), '%d %B %Y')`"
format: 
  html:
    embed-resources: true
    toc: true
    toc-location: left
execute:
  cache: true
---


```{r}
#| label: setup
#| include: false

library(ggplot2)
library(ggrepel)
library(meffonym)
library(here)
library(gt)
library(gtsummary)

# Read environment file
readRenviron(here("scripts/config.env"))

datadir <- Sys.getenv("datadir")
resultsdir <- Sys.getenv("resultsdir")
```

```{r}
#| label: load data
#| include: false

filename <- file.path(resultsdir, "combined-clin-pred-proteins.txt")
# Load data
data <- read.table(filename, header = T, sep = "\t", stringsAsFactors = F)

# Protein names
protein.names <- subset(meffonym::meffonym.models(full = T),
    grepl("^episcores", filename))$name
protein.names <- make.names(protein.names)

table(protein.names %in% colnames(data))
```

# Sample metadata
```{r}
#| label: tbl-summary

# Summary table
t1 <- tbl_summary(select(data, 
                         c(female, 
                           histology, 
                           age.at.diagnosis,
                           ethnicity,
                           race,
                           stage,
                           tumor.or.normal)), 
                  missing = "no",
                  label = list(
                    female = "Female",
                    histology = "Histology",
                    age.at.diagnosis = "Age at diagnosis",
                    ethnicity = "Ethnicity",
                    race = "Race",
                    stage = "Stage"), 
                  by = tumor.or.normal) |> 
  modify_caption("**Table 1: Cohort Characteristics**") |>
  bold_labels() |>
  as_gt() |>
  gt::cols_width(
    label ~ gt::px(250),    # Set first column to 250px
    everything() ~ gt::px(150))  # Set other columns to 150px

t1
```

# Analysis

## Tissue type vs protein levels

```{r}
#| label: glms-1

## GLM testing for an association between protein levels and tissue type  (tumor vs. normal)

## define glm formulae with pred.proteins as predictors of 'tumor.or.normal'
## tissue i.e. tumor.or.normal ~ pred.protein
formulae <- sapply(protein.names, function(i) {
  reformulate(i, response = "tumor")
}, simplify = F)

# run glms
fit <- sapply(formulae, function(i) {
  glm(i, data = data, family = binomial())
}, simplify = F)

fit.summary <- sapply(fit, function(i) {
  out <- summary(i)$coefficients
  out[, "Estimate"] <- out[, "Estimate"]
  out
}, simplify = F)

fit.coefs <- sapply(fit.summary, function(i) {
  i[2, c("Estimate", "Pr(>|z|)")]
}, simplify = F)
fit.coefs <- {
  x <- do.call(rbind, fit.coefs)
  data.frame(
    pred.protein = rownames(x),
    coef = x[, "Estimate"],
    p.value = x[, "Pr(>|z|)"]
  )
}

bonferroni <- -log10(0.05 / length(fit))

```

```{r}
#| label: figs-1
#| echo: false
#| fig-subcap: 
#|  - "Predicted proteins significantly associated with tissue type following multiple testing correction. Bonferroni threshold for significance is indicated by the dashed line."
#|  - "Volcano plot of model effect estimates. Bonferroni threshold for significance is indicated by the dashed line, points in are scaled by absolute effect size."

## Visualize results


fit.coefs |>
  ggplot(aes(x = pred.protein, y = -log10(p.value))) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  geom_text_repel(
    data = fit.coefs[which((-log10(fit.coefs$p.value) > bonferroni)), ],
    aes(x = pred.protein, y = -log10(p.value), label = pred.protein)
  ) +
  geom_hline(
    yintercept = bonferroni,
    linetype = "dashed"
  )

fit.coefs |>
  ggplot(aes(x = coef, y = -log10(p.value))) +
  geom_point() +
  geom_text_repel(
    data = fit.coefs[which((-log10(fit.coefs$p.value) > bonferroni)), ],
    aes(x = coef, y = -log10(p.value), label = pred.protein)
  ) +
  geom_hline(
    yintercept = bonferroni,
    linetype = "dashed"
  )

```


## Progression vs protein levels

```{r}
#| label: glms-2

## GLM testing for associations between protein levels and progression free interval (PFI)

# This analysis should be restricted to measurements taken from tumor samples

tumor.data <- subset(data, tumor == 1)

## define glm formulae with pred.proteins as predictors of pfi
## tissue i.e. pfi ~ pred.protein
formulae <- sapply(protein.names, function(i) {
  reformulate(i, response = "pfi")
}, simplify = F)

# run glms
fit <- sapply(formulae, function(i) {
  glm(i, data = tumor.data, family = binomial())
}, simplify = F)

fit.summary <- sapply(fit, function(i) {
  out <- summary(i)$coefficients
  out[, "Estimate"] <- out[, "Estimate"]
  out
}, simplify = F)

fit.coefs <- sapply(fit.summary, function(i) {
  i[2, c("Estimate", "Pr(>|z|)")]
}, simplify = F)
fit.coefs <- {
  x <- do.call(rbind, fit.coefs)
  data.frame(
    pred.protein = rownames(x),
    coef = x[, "Estimate"],
    p.value = x[, "Pr(>|z|)"]
  )
}
```

```{r}
#| label: figs-2
#| echo: false

## Visualize results


fit.coefs |>
  ggplot(aes(x = pred.protein, y = -log10(p.value))) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  geom_text_repel(
    data = fit.coefs[which((-log10(fit.coefs$p.value) > bonferroni)), ],
    aes(x = pred.protein, y = -log10(p.value), label = pred.protein)
  ) +
  geom_hline(
    yintercept = bonferroni,
    linetype = "dashed"
  )

fit.coefs |>
  ggplot(aes(x = coef, y = -log10(p.value))) +
  geom_point() +
  geom_text_repel(
    data = fit.coefs[which((-log10(fit.coefs$p.value) > bonferroni)), ],
    aes(x = coef, y = -log10(p.value), label = pred.protein)
  ) +
  geom_hline(
    yintercept = bonferroni,
    linetype = "dashed"
  )
  

```